import sqlite3
conn = sqlite3.connect('db/experiment.db')
cur = conn.cursor()
cur.execute('SELECT COUNT(*) FROM experiment')
print('experiment count:', cur.fetchone()[0])
cur.execute("SELECT column_name, data_type, is_id, order_index FROM column_def WHERE table_name='EXPERIMENT' ORDER BY order_index, column_name")
print('EXPERIMENT column_defs:')
for r in cur.fetchall(): print(r)
print()
cur.execute("PRAGMA table_info(experiment)")
print('experiment table columns:')
for r in cur.fetchall(): print(r)
conn.close()
